CREATE TABLE kelashutang (
  kode TEXT(6) NOT NULL,
  kuliah TEXT NOT NULL,
  jumlah NUMBER NOT NULL
);

INSERT INTO kelashutang VALUES ('IKH313', 'Jaringan Komputer dan Keamanan', 44);
INSERT INTO kelashutang VALUES ('IKL341', 'Struktur Data dan Algoritma', 43);
INSERT INTO kelashutang VALUES ('IKB451', 'Tugas Akhir II', 30);
INSERT INTO kelashutang VALUES ('IUM461', 'Struktur Diskrit I', 30);
INSERT INTO kelashutang VALUES ('IKB206', 'Kreativitas dan innovasi', 27);
INSERT INTO kelashutang VALUES ('IKB406', 'Metodologi Penelitian', 27);
INSERT INTO kelashutang VALUES ('IKH113', 'Praktikum Jaringan Komputer dan Keamanan', 22);
INSERT INTO kelashutang VALUES ('IKB405', 'Penulisan Ilmiah dan Laporan', 21);
INSERT INTO kelashutang VALUES ('IKB411', 'Konsep Teknologi Informasi dan Keamanan', 21);
INSERT INTO kelashutang VALUES ('IKH351', 'Organisasi dan Arsitektur Komputer', 21);
INSERT INTO kelashutang VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut', 19);
INSERT INTO kelashutang VALUES ('IKH151', 'Praktikum Organisasi dan Arsitektur Komputer', 19);
INSERT INTO kelashutang VALUES ('IKH309', 'Pengelolaan Jaringan Komputer', 18);
INSERT INTO kelashutang VALUES ('IKH311', 'Sistem Operasi', 15);
INSERT INTO kelashutang VALUES ('IKH323', 'Keamanan Informasi', 15);
INSERT INTO kelashutang VALUES ('IKH342', 'Pengolahan Sinyal Dijital', 14);
INSERT INTO kelashutang VALUES ('ISD314', 'Teknik Data Mining', 14);
INSERT INTO kelashutang VALUES ('ISM221', 'Ekonomi Informasi', 14);
INSERT INTO kelashutang VALUES ('IKB600', 'Tugas Akhir', 13);
INSERT INTO kelashutang VALUES ('IKH111', 'Praktikum Sistem Operasi', 13);
INSERT INTO kelashutang VALUES ('IKS413', 'Technopreneurship', 13);
INSERT INTO kelashutang VALUES ('IKL141', 'Praktikum Struktur Data dan Algorithma', 11);
INSERT INTO kelashutang VALUES ('IKS327', 'Desain Perangkat Lunak', 11);
INSERT INTO kelashutang VALUES ('UBA402', 'Internasionalisasi', 11);
INSERT INTO kelashutang VALUES ('IKH112', 'Praktikum Keamanan Sistem Operasi', 10);
INSERT INTO kelashutang VALUES ('IKH310', 'Sistem Keamanan Jaringan', 10);
INSERT INTO kelashutang VALUES ('IKL335', 'Dasar Pemrograman', 10);
INSERT INTO kelashutang VALUES ('IKG101', 'Praktikum Grafika Komputer', 9);
INSERT INTO kelashutang VALUES ('IKH318', 'Verifikasi dan Validasi Keamanan Informasi', 9);
INSERT INTO kelashutang VALUES ('IKL343', 'Disain dan Analisa Algoritma (MPM)', 9);
INSERT INTO kelashutang VALUES ('PDU212', 'Teori Warna', 9);
INSERT INTO kelashutang VALUES ('UKT101', 'Kuliah Kerja Lapangan', 9);
INSERT INTO kelashutang VALUES ('IKB450', 'Tugas Akhir I', 8);
INSERT INTO kelashutang VALUES ('IKP303', 'Mobile Programming', 8);
INSERT INTO kelashutang VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak', 8);
INSERT INTO kelashutang VALUES ('IKB205', 'Metodologi Penelitian dan Penulisan Ilmiah', 7);
INSERT INTO kelashutang VALUES ('IKG302', 'Pengolahan Citra', 7);
INSERT INTO kelashutang VALUES ('IKH314', 'Sistem Pengendalian Akses', 6);
INSERT INTO kelashutang VALUES ('IKP311', 'Pemrograman Berbasis Web', 6);
INSERT INTO kelashutang VALUES ('IKS301', 'Interaksi Manusia Dan Komputer', 6);
INSERT INTO kelashutang VALUES ('IKS304', 'Metode Berorientasi Obyek', 6);
INSERT INTO kelashutang VALUES ('ISM404', 'Proyek Rekayasa', 6);
INSERT INTO kelashutang VALUES ('IKH312', 'Keamanan Sistem Operasi', 5);
INSERT INTO kelashutang VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak', 5);
INSERT INTO kelashutang VALUES ('ISO101', 'Praktikum PSI', 5);
INSERT INTO kelashutang VALUES ('IKD312', 'Manajemen Data dan Informasi', 4);
INSERT INTO kelashutang VALUES ('IKG402', 'Grafika Komputer', 4);
INSERT INTO kelashutang VALUES ('IKH132', 'Praktikum Pengelolaan Jaringan Komputer', 4);
INSERT INTO kelashutang VALUES ('ISM403', 'Etika Agama Profesionalisme dan Legal', 4);
INSERT INTO kelashutang VALUES ('IIB205', 'Perilaku Organisasi', 3);
INSERT INTO kelashutang VALUES ('IKG321', 'Rekayasa Sistem Multimedia', 3);
INSERT INTO kelashutang VALUES ('IKH329', 'Pengelolaan Keamanan Informasi', 3);
INSERT INTO kelashutang VALUES ('IKP333', 'Cloud Computing', 3);
INSERT INTO kelashutang VALUES ('ISL304', 'Analisa Proses Bisnis', 3);
INSERT INTO kelashutang VALUES ('ISO301', 'Pengelolaan Sistem Informasi', 3);
INSERT INTO kelashutang VALUES ('IKG121', 'Praktikum Rekayasa Sistem Multimedia', 2);
INSERT INTO kelashutang VALUES ('IKP113', 'Praktikum Bahasa Pemrograman', 2);
INSERT INTO kelashutang VALUES ('ISM114', 'Praktikum Audit Sistem Informasi', 2);
INSERT INTO kelashutang VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi', 2);
INSERT INTO kelashutang VALUES ('IUM314', 'Kalkulus', 2);
INSERT INTO kelashutang VALUES ('IKG102', 'Praktikum Pengolahan Citra', 1);
INSERT INTO kelashutang VALUES ('IKH116', 'Praktikum Model dan Arsitektur Keamanan Informasi', 1);
INSERT INTO kelashutang VALUES ('IKL233', 'Pemodelan Geometri', 1);
INSERT INTO kelashutang VALUES ('IKS308', 'Sistem Informasi Manajemen', 1);
INSERT INTO kelashutang VALUES ('IKS328', 'ITSM', 1);
INSERT INTO kelashutang VALUES ('ISD305', 'Rekayasa Data dan Pengetahuan', 1);
INSERT INTO kelashutang VALUES ('ISM314', 'Audit Sistem Informasi', 1);
INSERT INTO kelashutang VALUES ('IUM263', 'Struktur Diskrit II', 1);
INSERT INTO kelashutang VALUES ('IUM351', 'Statistik Dasar', 1);
INSERT INTO kelashutang VALUES ('IKB250', 'Kuliah Kerja Profesi', 0);
INSERT INTO kelashutang VALUES ('IKG304', 'Seni Animasi', 0);
INSERT INTO kelashutang VALUES ('IKH109', 'Praktikum Pengelolaan Keamanan Informasi', 0);
INSERT INTO kelashutang VALUES ('IKH331', 'Sistem Terdistribusi', 0);
INSERT INTO kelashutang VALUES ('IKL133', 'Praktikum Pemodelan Geometri', 0);
INSERT INTO kelashutang VALUES ('IKP102', 'Praktikum Pemrograman Berbasis Komponen', 0);
INSERT INTO kelashutang VALUES ('IKP111', 'Praktikum Pemrograman Berbasis Web', 0);
INSERT INTO kelashutang VALUES ('IKP302', 'Pemprog Berbasis Komponen', 0);
INSERT INTO kelashutang VALUES ('IKS108', 'Praktikum SIM', 0);
INSERT INTO kelashutang VALUES ('IKS123', 'Praktikum Analisis dan Pemodelan Perangkat Lunak', 0);
INSERT INTO kelashutang VALUES ('IKS126', 'Praktikum Desain Perangkat Lunak', 0);
INSERT INTO kelashutang VALUES ('IKS318', 'Verifikasi dan Validasi Perangkat Lunak', 0);
INSERT INTO kelashutang VALUES ('ISD312', 'Information Retrieval', 0);
INSERT INTO kelashutang VALUES ('ISL303', 'Pengetahuan Bisnis', 0);
INSERT INTO kelashutang VALUES ('ISL305', 'Business Intelligence', 0);
INSERT INTO kelashutang VALUES ('ISM313', 'Pengantar Audit Sistem Informasi', 0);
INSERT INTO kelashutang VALUES ('ISM316', 'Manajemen Pemasaran IT', 0);
INSERT INTO kelashutang VALUES ('UKT300', 'Kuliah Usaha Mandiri Ilmu Teknik Terapan', 0);
INSERT INTO kelashutang VALUES ('UKW400', 'Pancasila dan Kewarganegaraan', 0);
