CREATE TABLE IF NOT EXISTS mastercuriculum (
  kode TEXT(6) NOT NULL
  , nama TEXT NOT NULL
  , mpm TEXT(1) NOT NULL
  , term TEXT(1) NOT NULL
  , semester NUMBER(2) NOT NULL
  , prodi TEXT(1) NOT NULL
);

INSERT INTO mastercuriculum VALUES ('ISL304', 'Analisa Proses Bisnis (MPK)', '1', '4', 4, '5');
INSERT INTO mastercuriculum VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak', '1', '3', 3, '5');
INSERT INTO mastercuriculum VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak (MPK)', '1', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak (MPK)', '1', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak (MPK)', '1', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak (MPK)', '1', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKS326', 'Arsitektur Enterprise', '0', '6', 6, '5');
INSERT INTO mastercuriculum VALUES ('ISM314', 'Audit Sistem Informasi', '1', '0', 0, '4');
INSERT INTO mastercuriculum VALUES ('ISM314', 'Audit Sistem Informasi (MPK)', '1', '6', 6, '5');
INSERT INTO mastercuriculum VALUES ('IKP213', 'Bahasa Pemrograman', '0', '7', 7, '2');
INSERT INTO mastercuriculum VALUES ('ISA301', 'Bisnis Berbasis Internet', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('ISA301', 'Bisnis Berbasis Internet', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('ISL305', 'Business Intelligence', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('ISL305', 'Business Intelligence', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('IKP333', 'Cloud Computing', '0', '0', 0, '4');
INSERT INTO mastercuriculum VALUES ('IKP333', 'Cloud Computing', '0', '0', 0, '2');
INSERT INTO mastercuriculum VALUES ('IKP333', 'Cloud Computing', '0', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('IKL335', 'Dasar Pemrograman', '1', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IKL335', 'Dasar Pemrograman (MPK)', '1', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('ISD301', 'Data Warehouse', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('IKL343', 'Desain dan Analisis Algoritma', '0', '6', 6, '2');
INSERT INTO mastercuriculum VALUES ('IKS327', 'Desain Perangkat Lunak', '1', '4', 4, '3');
INSERT INTO mastercuriculum VALUES ('IKS327', 'Desain Perangkat Lunak', '1', '4', 4, '5');
INSERT INTO mastercuriculum VALUES ('IKS327', 'Desain Perangkat Lunak (MPK)', '1', '4', 4, '2');
INSERT INTO mastercuriculum VALUES ('ISM221', 'Ekonomi Informasi', '0', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('ISM221', 'Ekonomi Informasi', '0', '5', 5, '4');
INSERT INTO mastercuriculum VALUES ('ISM221', 'Ekonomi Informasi', '0', '5', 5, '2');
INSERT INTO mastercuriculum VALUES ('ISM221', 'Ekonomi Informasi', '0', '4', 4, '5');
INSERT INTO mastercuriculum VALUES ('ISM403', 'Etika Agama Profesionalisme dan Legal', '0', '6', 6, '5');
INSERT INTO mastercuriculum VALUES ('ISM403', 'Etika Agama Profesionalisme dan Legal', '0', '6', 6, '3');
INSERT INTO mastercuriculum VALUES ('ISM403', 'Etika Agama Profesionalisme dan Legal', '0', '6', 6, '4');
INSERT INTO mastercuriculum VALUES ('ISM403', 'Etika Agama Profesionalisme dan Legal', '0', '6', 6, '2');
INSERT INTO mastercuriculum VALUES ('IKH328', 'Forensik Komputer dan Jaringan (MPK)', '1', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('IKH328', 'Forensik Komputer dan Jaringan (MPK)', '1', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('IKG401', 'Grafika Komputer (MPK)', '1', '4', 4, '3');
INSERT INTO mastercuriculum VALUES ('ISD312', 'Information Retrieval', '0', '0', 0, '4');
INSERT INTO mastercuriculum VALUES ('ISD312', 'Information Retrieval', '0', '0', 0, '2');
INSERT INTO mastercuriculum VALUES ('ISD312', 'Information Retrieval', '0', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('IKS301', 'Interaksi Manusia dan Komputer', '0', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKS301', 'Interaksi Manusia dan Komputer', '0', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKS301', 'Interaksi Manusia dan Komputer', '0', '5', 5, '5');
INSERT INTO mastercuriculum VALUES ('UBA402', 'Internasionalisasi', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('UBA402', 'Internasionalisasi', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IKS328', 'ITSM (Information Technology Service Management)', '0', '7', 7, '5');
INSERT INTO mastercuriculum VALUES ('IKH313', 'Jaringan Komputer dan Keamanan', '1', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKH313', 'Jaringan Komputer dan Keamanan (MPK)', '1', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IUM314', 'Kalkulus', '0', '3', 3, '4');
INSERT INTO mastercuriculum VALUES ('IKH327', 'Keamanan Fisik', '0', '6', 6, '4');
INSERT INTO mastercuriculum VALUES ('IKH323', 'Keamanan Informasi', '1', '7', 7, '5');
INSERT INTO mastercuriculum VALUES ('IKH323', 'Keamanan Informasi (MPK)', '1', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKH323', 'Keamanan Informasi (MPK)', '1', '3', 3, '4');
INSERT INTO mastercuriculum VALUES ('IKH323', 'Keamanan Informasi (MPK)', '1', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKH319', 'Keamanan Operasional', '0', '5', 5, '4');
INSERT INTO mastercuriculum VALUES ('IKH324', 'Keamanan Pengembangan Aplikasi', '0', '7', 7, '4');
INSERT INTO mastercuriculum VALUES ('IKH312', 'Keamanan Sistem Operasi', '0', '3', 3, '4');
INSERT INTO mastercuriculum VALUES ('IKA301', 'Kecerdasan Buatan', '0', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('IKA301', 'Kecerdasan Buatan', '0', '0', 0, '4');
INSERT INTO mastercuriculum VALUES ('IKA301', 'Kecerdasan Buatan', '0', '0', 0, '2');
INSERT INTO mastercuriculum VALUES ('ISL302', 'Komunikasi Bisnis dan Teknis', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('IKB411', 'Konsep Teknologi Informasi dan Keamanan', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IKB411', 'Konsep Teknologi Informasi dan Keamanan', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IKB206', 'Kreativitas dan Inovasi', '0', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('IKB206', 'Kreativitas dan Inovasi', '0', '5', 5, '4');
INSERT INTO mastercuriculum VALUES ('IKB206', 'Kreativitas dan Inovasi', '0', '5', 5, '2');
INSERT INTO mastercuriculum VALUES ('IKB206', 'Kreativitas dan Inovasi', '0', '5', 5, '5');
INSERT INTO mastercuriculum VALUES ('UKT101', 'Kuliah Kerja Lapangan', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('UKT101', 'Kuliah Kerja Lapangan', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKB250', 'Kuliah Kerja Profesi', '0', 'A', 7, '3');
INSERT INTO mastercuriculum VALUES ('IKB250', 'Kuliah Kerja Profesi', '0', 'A', 7, '4');
INSERT INTO mastercuriculum VALUES ('IKB250', 'Kuliah Kerja Profesi', '0', 'A', 7, '2');
INSERT INTO mastercuriculum VALUES ('IKB250', 'Kuliah Kerja Profesi', '0', 'A', 7, '5');
INSERT INTO mastercuriculum VALUES ('UKT300', 'KUM-ITT', '0', '0', 0, '4');
INSERT INTO mastercuriculum VALUES ('UKT300', 'KUM-ITT', '0', '0', 0, '2');
INSERT INTO mastercuriculum VALUES ('UKT300', 'KUM-ITT', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('UKT300', 'KUM-ITT', '0', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak', '0', '6', 6, '3');
INSERT INTO mastercuriculum VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak', '0', '0', 0, '4');
INSERT INTO mastercuriculum VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak', '0', '6', 6, '2');
INSERT INTO mastercuriculum VALUES ('IKD312', 'Manajemen Data dan Informasi', '1', '3', 3, '4');
INSERT INTO mastercuriculum VALUES ('IKD312', 'Manajemen Data dan Informasi (MPK)', '1', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKD312', 'Manajemen Data dan Informasi (MPK)', '1', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKD312', 'Manajemen Data dan Informasi (MPK)', '1', '3', 3, '5');
INSERT INTO mastercuriculum VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut', '0', '7', 7, '3');
INSERT INTO mastercuriculum VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut', '0', '7', 7, '2');
INSERT INTO mastercuriculum VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut', '0', '5', 5, '5');
INSERT INTO mastercuriculum VALUES ('ISM317', 'Manajemen Dokumen', '0', '0', 0, '2');
INSERT INTO mastercuriculum VALUES ('ISM317', 'Manajemen Dokumen', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('ISM315', 'Manajemen Keuangan', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('ISM316', 'Manajemen Pemasaran IT', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('ISM312', 'Manajemen Pengetahuan', '0', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('ISM312', 'Manajemen Pengetahuan', '0', '0', 0, '4');
INSERT INTO mastercuriculum VALUES ('ISM312', 'Manajemen Pengetahuan', '0', '0', 0, '2');
INSERT INTO mastercuriculum VALUES ('ISM202', 'Manajemen Pengetahuan', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('ISM202', 'Manajemen Pengetahuan', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi', '1', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi (MPK)', '1', '4', 4, '3');
INSERT INTO mastercuriculum VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi (MPK)', '1', '4', 4, '2');
INSERT INTO mastercuriculum VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi (MPK)', '1', '4', 4, '5');
INSERT INTO mastercuriculum VALUES ('IKS304', 'Metode Berorientasi Objek', '1', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKS304', 'Metode Berorientasi Objek', '1', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('IKS304', 'Metode Berorientasi Objek (MPK)', '1', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKB406', 'Metodologi Penelitian', '0', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('IKB406', 'Metodologi Penelitian', '0', '5', 5, '4');
INSERT INTO mastercuriculum VALUES ('IKB406', 'Metodologi Penelitian', '0', '5', 5, '2');
INSERT INTO mastercuriculum VALUES ('IKB406', 'Metodologi Penelitian', '0', '5', 5, '5');
INSERT INTO mastercuriculum VALUES ('IKP303', 'Mobile Programming', '0', '5', 5, '2');
INSERT INTO mastercuriculum VALUES ('IKP303', 'Mobile Programming', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('IKH316', 'Model dan Arsitektur Keamanan Informasi (MPK)', '1', '5', 5, '4');
INSERT INTO mastercuriculum VALUES ('IKH351', 'Organisasi dan Arsitektur Komputer', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IKH351', 'Organisasi dan Arsitektur Komputer', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('UKW400', 'Pancasila dan Kewarganegaraan', '0', '4', 4, '3');
INSERT INTO mastercuriculum VALUES ('UKW400', 'Pancasila dan Kewarganegaraan', '0', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('UKW400', 'Pancasila dan Kewarganegaraan', '0', '4', 4, '2');
INSERT INTO mastercuriculum VALUES ('UKW400', 'Pancasila dan Kewarganegaraan', '0', '4', 4, '5');
INSERT INTO mastercuriculum VALUES ('IKL233', 'Pemodelan Geometri (MPK)', '1', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('IKP302', 'Pemrograman Berbasis Komponen', '0', '4', 4, '2');
INSERT INTO mastercuriculum VALUES ('IKP311', 'Pemrograman Berbasis Web', '0', '4', 4, '2');
INSERT INTO mastercuriculum VALUES ('IKP311', 'Pemrograman Berbasis Web', '0', '0', 0, '5');
INSERT INTO mastercuriculum VALUES ('ISM313', 'Pengantar Audit Sistem Informasi (MPK)', '1', '5', 5, '5');
INSERT INTO mastercuriculum VALUES ('IKH309', 'Pengelolaan Jaringan Komputer', '0', '7', 7, '4');
INSERT INTO mastercuriculum VALUES ('IKH309', 'Pengelolaan Jaringan Komputer', '0', '3', 3, '5');
INSERT INTO mastercuriculum VALUES ('IKH329', 'Pengelolaan Keamanan Informasi (MPK)', '1', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('ISO301', 'Pengelolaan Sistem Informasi (MPK)', '1', '4', 4, '5');
INSERT INTO mastercuriculum VALUES ('ISL303', 'Pengetahuan Bisnis', '0', '3', 3, '5');
INSERT INTO mastercuriculum VALUES ('IKG302', 'Pengolahan Citra', '0', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('IKH342', 'Pengolahan Sinyal Digital', '0', '4', 4, '3');
INSERT INTO mastercuriculum VALUES ('IKB405', 'Penulisan ilmiah dan Laporan', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKB405', 'Penulisan Ilmiah dan Laporan', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKH326', 'Perencanaan Kontinyuitas Bisnis', '1', '0', 0, '2');
INSERT INTO mastercuriculum VALUES ('IKH326', 'Perencanaan Kontinyuitas Bisnis', '1', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('IKH326', 'Perencanaan Kontinyuitas Bisnis (MPK)', '1', '5', 5, '4');
INSERT INTO mastercuriculum VALUES ('IIB205', 'Perilaku Organisasi', '0', '3', 3, '5');
INSERT INTO mastercuriculum VALUES ('IKH116', 'Praktikum Analisis dan Pemodelan Keamanan Informasi', '0', '5', 5, '4');
INSERT INTO mastercuriculum VALUES ('IKS123', 'Praktikum Analisis dan Pemodelan Perangkat Lunak', '0', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKS123', 'Praktikum Analisis dan Pemodelan Perangkat Lunak', '0', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKS123', 'Praktikum Analisis dan Pemodelan Perangkat Lunak', '0', '3', 3, '5');
INSERT INTO mastercuriculum VALUES ('ISM114', 'Praktikum Audit Sistem Informasi', '0', '6', 6, '5');
INSERT INTO mastercuriculum VALUES ('IKP113', 'Praktikum Bahasa Pemrograman', '0', '7', 7, '2');
INSERT INTO mastercuriculum VALUES ('IKL135', 'Praktikum Dasar Pemrograman', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IKL135', 'Praktikum Dasar Pemrograman', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IKS126', 'Praktikum Desain Perangkat Lunak', '0', '4', 4, '3');
INSERT INTO mastercuriculum VALUES ('IKS126', 'Praktikum Desain Perangkat Lunak', '0', '4', 4, '2');
INSERT INTO mastercuriculum VALUES ('IKS126', 'Praktikum Desain Perangkat Lunak', '0', '4', 4, '5');
INSERT INTO mastercuriculum VALUES ('IKH128', 'Praktikum Forensik Komputer dan Jaringan', '0', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('IKG101', 'Praktikum Grafika Komputer', '0', '4', 4, '3');
INSERT INTO mastercuriculum VALUES ('IKH113', 'Praktikum Jaringan Komputer dan Keamanan', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKH113', 'Praktikum Jaringan Komputer dan Keamanan', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKH123', 'Praktikum Keamanan Informasi', '0', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKH123', 'Praktikum Keamanan Informasi', '0', '3', 3, '4');
INSERT INTO mastercuriculum VALUES ('IKH123', 'Praktikum Keamanan Informasi', '0', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKH110', 'Praktikum Keamanan Jaringan Komputer', '0', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('IKH119', 'Praktikum Keamanan Operasional', '0', '5', 5, '4');
INSERT INTO mastercuriculum VALUES ('IKH112', 'Praktikum Keamanan Sistem Operasi', '0', '3', 3, '4');
INSERT INTO mastercuriculum VALUES ('IKD112', 'Praktikum Manajemen Data dan Informasi', '0', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKD112', 'Praktikum Manajemen Data dan Informasi', '0', '3', 3, '4');
INSERT INTO mastercuriculum VALUES ('IKD112', 'Praktikum Manajemen Data dan Informasi', '0', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKD112', 'Praktikum Manajemen Data dan Informasi', '0', '3', 3, '5');
INSERT INTO mastercuriculum VALUES ('IKD123', 'Praktikum Manajemen Data dan Informasi Lanjut', '0', '7', 7, '3');
INSERT INTO mastercuriculum VALUES ('IKD123', 'Praktikum Manajemen Data dan Informasi Lanjut', '0', '7', 7, '2');
INSERT INTO mastercuriculum VALUES ('IKD123', 'Praktikum Manajemen Data dan Informasi Lanjut', '0', '5', 5, '5');
INSERT INTO mastercuriculum VALUES ('IKS104', 'Praktikum Metode Berorientasi Objek', '0', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IKS104', 'Praktikum Metode Berorientasi Objek', '0', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKP103', 'Praktikum Mobile Programming', '0', '5', 5, '2');
INSERT INTO mastercuriculum VALUES ('IKH151', 'Praktikum Organisasi dan Arsitektur Komputer', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IKH151', 'Praktikum Organisasi dan Arsitektur Komputer', '0', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IKL133', 'Praktikum Pemodelan Geometri', '0', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('IKP102', 'Praktikum Pemrograman Berbasis Komponen', '0', '4', 4, '2');
INSERT INTO mastercuriculum VALUES ('IKP111', 'Praktikum Pemrograman Berbasis Web', '0', '4', 4, '2');
INSERT INTO mastercuriculum VALUES ('IKH132', 'Praktikum Pengelolaan Jaringan Komputer', '0', '7', 7, '4');
INSERT INTO mastercuriculum VALUES ('IKH109', 'Praktikum Pengelolaan Keamanan Informasi', '0', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('ISO101', 'Praktikum Pengelolaan Sistem Informasi', '0', '4', 4, '5');
INSERT INTO mastercuriculum VALUES ('IKG102', 'Praktikum Pengolahan Citra', '0', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('IKH126', 'Praktikum Perencanaan Kontinyuitas Bisnis', '0', '5', 5, '4');
INSERT INTO mastercuriculum VALUES ('IKG121', 'Praktikum Rekayasa Sistem Multimedia', '0', '6', 6, '3');
INSERT INTO mastercuriculum VALUES ('IKS108', 'Praktikum Sistem Informasi Manajemen', '0', '3', 3, '5');
INSERT INTO mastercuriculum VALUES ('IKH111', 'Praktikum Sistem Operasi', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKH111', 'Praktikum Sistem Operasi', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKH114', 'Praktikum Sistem Pengendalian Akses', '0', '3', 3, '4');
INSERT INTO mastercuriculum VALUES ('IKL141', 'Praktikum Struktur Data dan Algoritma', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKL141', 'Praktikum Struktur Data dan Algoritma', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKH118', 'Praktikum Verifikasi dan Validasi Keamanan Informasi', '0', '6', 6, '4');
INSERT INTO mastercuriculum VALUES ('IKS118', 'Praktikum Verifikasi dan Validasi Perangkat Lunak', '0', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('IKS118', 'Praktikum Verifikasi dan Validasi Perangkat Lunak', '0', '5', 5, '2');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '3');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '3');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '3');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '2');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '2');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '2');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '5');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '5');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '4');
INSERT INTO mastercuriculum VALUES ('ISM404', 'Proyek Rekayasa', '0', '6', 6, '4');
INSERT INTO mastercuriculum VALUES ('ISD305', 'Rekayasa Data dan Pengetahuan', '0', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('IKG321', 'Rekayasa Sistem Multimedia', '1', '0', 0, '4');
INSERT INTO mastercuriculum VALUES ('IKG321', 'Rekayasa Sistem Multimedia (MPK)', '1', '6', 6, '3');
INSERT INTO mastercuriculum VALUES ('IKG304', 'Seni Animasi', '0', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('IKG311', 'Sistem Informasi Geografi', '0', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('IKS308', 'Sistem Informasi Manajemen (MPK)', '1', '3', 3, '5');
INSERT INTO mastercuriculum VALUES ('IKH310', 'Sistem Keamanan Jaringan', '0', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('IKH310', 'Sistem Keamanan Jaringan', '0', '4', 4, '4');
INSERT INTO mastercuriculum VALUES ('IKH311', 'Sistem Operasi (MPK)', '1', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKH311', 'Sistem Operasi (MPK)', '1', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKH314', 'Sistem Pengendalian Akses', '1', '0', 0, '2');
INSERT INTO mastercuriculum VALUES ('IKH314', 'Sistem Pengendalian Akses', '1', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('IKH314', 'Sistem Pengendalian Akses (MPK)', '1', '3', 3, '4');
INSERT INTO mastercuriculum VALUES ('IKH331', 'Sistem Terdistribusi', '0', '5', 5, '2');
INSERT INTO mastercuriculum VALUES ('IKH331', 'Sistem Terdistribusi', '0', '5', 5, '2');
INSERT INTO mastercuriculum VALUES ('IKL341', 'Struktur Data dan Algoritma', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKL341', 'Struktur Data dan Algoritma', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IUM461', 'Struktur Diskrit I (MPK)', '1', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IUM461', 'Struktur Diskrit I (MPK)', '1', '1', 1, '1');
INSERT INTO mastercuriculum VALUES ('IUM263', 'Struktur Diskrit II', '0', '3', 3, '3');
INSERT INTO mastercuriculum VALUES ('IUM263', 'Struktur Diskrit II', '0', '3', 3, '2');
INSERT INTO mastercuriculum VALUES ('IKS413', 'Technopreneurship', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('IKS413', 'Technopreneurship', '0', '2', 2, '1');
INSERT INTO mastercuriculum VALUES ('ISD314', 'Teknik Data Mining', '0', '0', 0, '2');
INSERT INTO mastercuriculum VALUES ('ISD314', 'Teknik Data Mining', '0', '0', 0, '3');
INSERT INTO mastercuriculum VALUES ('PDU212', 'Teori Warna', '0', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('IKB450', 'Tugas Akhir I', '0', 'A', 7, '5');
INSERT INTO mastercuriculum VALUES ('IKB450', 'Tugas Akhir I', '0', 'A', 7, '3');
INSERT INTO mastercuriculum VALUES ('IKB450', 'Tugas Akhir I', '0', 'A', 7, '4');
INSERT INTO mastercuriculum VALUES ('IKB450', 'Tugas Akhir I', '0', 'A', 7, '2');
INSERT INTO mastercuriculum VALUES ('IKB451', 'Tugas Akhir II', '0', 'A', 8, '3');
INSERT INTO mastercuriculum VALUES ('IKB451', 'Tugas Akhir II', '0', 'A', 8, '2');
INSERT INTO mastercuriculum VALUES ('IKB451', 'Tugas Akhir II', '0', 'A', 8, '5');
INSERT INTO mastercuriculum VALUES ('IKB451', 'Tugas Akhir II', '0', 'A', 8, '4');
INSERT INTO mastercuriculum VALUES ('IKH318', 'Verifikasi dan Validasi Keamanan Informasi (MPM)', '1', '6', 6, '4');
INSERT INTO mastercuriculum VALUES ('IKS318', 'Verifikasi dan Validasi Perangkat Lunak', '1', '5', 5, '3');
INSERT INTO mastercuriculum VALUES ('IKS318', 'Verifikasi dan Validasi Perangkat Lunak (MPK)', '1', '5', 5, '2');
INSERT INTO mastercuriculum VALUES ('IKS319', 'Verifikasi dan Validasi Sistem Informasi', '0', '5', 5, '5');
INSERT INTO mastercuriculum VALUES ('ISD313', 'Virtualisasi', '0', '0', 0, '4');
INSERT INTO mastercuriculum VALUES ('ISD313', 'Virtualisasi', '0', '0', 0, '2');

