CREATE TABLE IF NOT EXISTS mastercourse (
  kode TEXT(6) PRIMARY KEY
  , nama TEXT NOT NULL
  , english TEXT
);


INSERT INTO mastercourse VALUES ('IKB206', 'Kreativitas dan innovasi', 'Creativity and Innovation');
INSERT INTO mastercourse VALUES ('ISM221', 'Ekonomi Informasi', 'Information Economy');
INSERT INTO mastercourse VALUES ('IUM461', 'Struktur Diskrit I', 'Discrete Structure I');
INSERT INTO mastercourse VALUES ('IKB406', 'Metodologi Penelitian', 'Research Methodology');
INSERT INTO mastercourse VALUES ('IKB411', 'Konsep Teknologi Informasi dan Keamanan', 'Concept of Information and Security Technology');
INSERT INTO mastercourse VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi', 'Project Management of Information Technology');
INSERT INTO mastercourse VALUES ('IKB405', 'Penulisan Ilmiah dan Laporan', 'Academic and Report Writing');
INSERT INTO mastercourse VALUES ('IKH113', 'Praktikum Jaringan Komputer dan Keamanan', 'Labwork of Computer Network and Security');
INSERT INTO mastercourse VALUES ('IKH313', 'Jaringan Komputer dan Keamanan', 'Computer Network and Security');
INSERT INTO mastercourse VALUES ('IKH309', 'Pengelolaan Jaringan Komputer', 'Managemen of Computer Network');
INSERT INTO mastercourse VALUES ('IKH151', 'Prak. Organisasi dan Arsitektur Komputer', 'Labwork of Computer Organization and Architecture');
INSERT INTO mastercourse VALUES ('IKH351', 'Organisasi dan Arsitektur Komputer', 'Computer Organisation and Architecture');
INSERT INTO mastercourse VALUES ('IKH111', 'Praktikum Sistem Operasi', 'Laboratory Works of Operating System');
INSERT INTO mastercourse VALUES ('IKH323', 'Keamanan Informasi', 'Information Security');
INSERT INTO mastercourse VALUES ('IKH311', 'Sistem Operasi', 'Operating System');
INSERT INTO mastercourse VALUES ('IKL141', 'Prak Struktur Data dan Algorithma', 'Data Structure and Algorithm Lab');
INSERT INTO mastercourse VALUES ('IKL341', 'Struktur Data dan Algoritma', 'Data Structures and Algorithm');
INSERT INTO mastercourse VALUES ('IKL135', 'Praktikum Dasar Pemrograman', 'Labwork of Programming Basics');
INSERT INTO mastercourse VALUES ('IKL335', 'Dasar Pemrograman', 'Programming Basics');
INSERT INTO mastercourse VALUES ('IKS123', 'Praktikum Analisis dan Pemodelan Perangkat Lunak', 'Labwork of Software Analysis dan Modelling');
INSERT INTO mastercourse VALUES ('IKS301', 'Interaksi Manusia Dan Komputer', 'Human Computer Interface');
INSERT INTO mastercourse VALUES ('IKS126', 'Praktikum Desain Perangkat Lunak', 'Labwork of Software Design');
INSERT INTO mastercourse VALUES ('IKS327', 'Desain Perangkat Lunak', 'Software Design');
INSERT INTO mastercourse VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak', 'Software Analysis and Modelling');
INSERT INTO mastercourse VALUES ('IKS319', 'Verifikasi dan Validasi SI', 'Information System Verification and Validation');
INSERT INTO mastercourse VALUES ('IKD112', 'Praktikum Manajemen Data dan Informasi', 'Labwork of Data and Information Management');
INSERT INTO mastercourse VALUES ('IKS328', 'ITSM', 'ITSM');
INSERT INTO mastercourse VALUES ('IKD312', 'Manajemen Data dan Informasi', 'Data and Information Management');
INSERT INTO mastercourse VALUES ('ISM313', 'Pengantar Audit Sistem Informasi', 'Intoduction of Informmation Sistem Audit');
INSERT INTO mastercourse VALUES ('ISM114', 'Praktikum Audit Sistem Informasi', 'Labwork of Information System Audit');
INSERT INTO mastercourse VALUES ('ISM314', 'Audit Sistem Informasi', 'Information System Audit');
INSERT INTO mastercourse VALUES ('IKD123', 'Praktikum Manajemen Data dan Informasi Lanjut', 'Labwork of Data and Information Management');
INSERT INTO mastercourse VALUES ('ISO101', 'Praktikum PSI', 'Labwork of Information System Management');
INSERT INTO mastercourse VALUES ('IKS108', 'Praktikum SIM', 'Labwork of Management Information System');
INSERT INTO mastercourse VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut', 'Advance of Data and Information Management');
INSERT INTO mastercourse VALUES ('ISO301', 'Pengelolaan Sistem Informasi', 'System Information Management');
INSERT INTO mastercourse VALUES ('IKS308', 'Sistem Informasi Manajemen', 'Management Information System');
INSERT INTO mastercourse VALUES ('IKS326', 'Arsitektur Enterprise', 'Enterprize Architecture');
INSERT INTO mastercourse VALUES ('ISL304', 'Analisa Proses Bisnis', 'Business Process Analysis');
INSERT INTO mastercourse VALUES ('IIB205', 'Perilaku Organisasi', 'Organizational Behaviour');
INSERT INTO mastercourse VALUES ('ISL303', 'Pengetahuan Bisnis', 'Business Knowledge Concept');
INSERT INTO mastercourse VALUES ('IKB451', 'Tugas Akhir II', 'Final Assignment II');
INSERT INTO mastercourse VALUES ('IKB250', 'Kuliah Kerja Profesi', 'Job Training');
INSERT INTO mastercourse VALUES ('UKW400', 'Pancasila dan Kewarganegaraan', 'Pancasila and Civics');
INSERT INTO mastercourse VALUES ('UKT101', 'Kuliah Kerja Lapangan', 'Fieldwork');
INSERT INTO mastercourse VALUES ('ISM403', 'Etika, Agama, Profesionalisme, dan Legal', 'Ethics, Religion, Professional, and Legal');
INSERT INTO mastercourse VALUES ('IKB450', 'Tugas Akhir I', 'Final Assignment I');
INSERT INTO mastercourse VALUES ('ISM404', 'Proyek Rekayasa', 'Engineering Project');
INSERT INTO mastercourse VALUES ('UBA402', 'Internasionalisasi', 'Internationalization');
INSERT INTO mastercourse VALUES ('IKS413', 'Technopreneurship', 'Techopreneurship');
INSERT INTO mastercourse VALUES ('ISA301', 'Bisnis Berbasis Internet', 'E-Business');
INSERT INTO mastercourse VALUES ('ISL301', 'Pengembangan Aplikasi Berbasis Web', 'Web-based Application Development');
INSERT INTO mastercourse VALUES ('IKG321', 'Rekayasa Sistem Multimedia', 'Multimedia System Engineering');
INSERT INTO mastercourse VALUES ('IKG311', 'Sistem Informasi Geografi', 'Geographic Information System');

CREATE TABLE IF NOT EXISTS coursegroup (
  code NUMBER PRIMARY KEY
  , name TEXT NOT NULL UNIQUE
  );

INSERT INTO coursegroup VALUES (1, 'MPK');
INSERT INTO coursegroup VALUES (2, 'MKK');
INSERT INTO coursegroup VALUES (3, 'MKB');
INSERT INTO coursegroup VALUES (4, 'MPB');
INSERT INTO coursegroup VALUES (5, 'MBB');
INSERT INTO coursegroup VALUES (6, 'JARKOM');
INSERT INTO coursegroup VALUES (7, 'PILIHAN JARKOM');
INSERT INTO coursegroup VALUES (8, 'DASAR MATEMATIK DAN REKAYASA KI');
INSERT INTO coursegroup VALUES (9, 'INFRASTRUKTUR TEKNOLOGI INFORMASI KI');
INSERT INTO coursegroup VALUES (10, 'PEMROGRAMAN KOMPUTER KI');
INSERT INTO coursegroup VALUES (11, 'KEAMANAN INFORMASI');
INSERT INTO coursegroup VALUES (12, 'PROFESIONALISME DAN KEWIRAUSAHAAN');
INSERT INTO coursegroup VALUES (13, 'PILIHAN KEAMANAN INFORMASI');
INSERT INTO coursegroup VALUES (14, 'DASAR MATEMATIKA DAN REKAYASA');
INSERT INTO coursegroup VALUES (15, 'INFRASTRUKTUR TEKNOLOGI INFORMASI');
INSERT INTO coursegroup VALUES (16, 'PEMROGRAMAN KOMPUTER SI');
INSERT INTO coursegroup VALUES (17, 'REKAYASA PERANGKAT LUNAK');
INSERT INTO coursegroup VALUES (18, 'SISTEM INFORMASI');
INSERT INTO coursegroup VALUES (19, 'BISNIS');
INSERT INTO coursegroup VALUES (20, 'PILIHAN');
INSERT INTO coursegroup VALUES (21, 'SIMPANAN');

-- INSERT INTO kurikulum VALUES ('IKS319', 'Verifikasi dan Validasi Sistem Informasi');
-- INSERT INTO kurikulum VALUES ('IKS318', 'Verifikasi dan Validasi  Perangkat Lunak');
-- INSERT INTO kurikulum VALUES ('IKH318', 'Verifikasi dan Validasi  Keamanan Informasi');
-- INSERT INTO kurikulum VALUES ('IKB451', 'Tugas Akhir II');
-- INSERT INTO kurikulum VALUES ('IKB450', 'Tugas Akhir I');
-- INSERT INTO kurikulum VALUES ('PDU212', 'Teori Warna');
-- INSERT INTO kurikulum VALUES ('IKS413', 'Technopreneurship');
-- INSERT INTO kurikulum VALUES ('IUM263', 'Struktur Diskrit II');
-- INSERT INTO kurikulum VALUES ('IUM461', 'Struktur Diskrit I');
-- INSERT INTO kurikulum VALUES ('IKL341', 'Struktur Data dan Algoritma');
-- INSERT INTO kurikulum VALUES ('IKH331', 'Sistem Terdistribusi');
-- INSERT INTO kurikulum VALUES ('IKH314', 'Sistem Pengendalian Akses');
-- INSERT INTO kurikulum VALUES ('IKH311', 'Sistem Operasi');
-- INSERT INTO kurikulum VALUES ('IKH310', 'Sistem Keamanan Jaringan');
-- INSERT INTO kurikulum VALUES ('IKS308', 'Sistem Informasi Manajemen');
-- INSERT INTO kurikulum VALUES ('IKG321', 'Rekayasa Sistem Multimedia');
-- INSERT INTO kurikulum VALUES ('ISM404', 'Proyek Rekayasa');
-- INSERT INTO kurikulum VALUES ('IKS118', 'Praktikum Verifikasi dan Validasi Perangkat Lunak');
-- INSERT INTO kurikulum VALUES ('IKH118', 'Praktikum Verifikasi dan Validasi Keamanan Informasi');
-- INSERT INTO kurikulum VALUES ('IKL141', 'Praktikum Struktur Data dan Algoritma');
-- INSERT INTO kurikulum VALUES ('IKH114', 'Praktikum Sistem Pengendalian Akses');
-- INSERT INTO kurikulum VALUES ('IKH111', 'Praktikum Sistem Operasi');
-- INSERT INTO kurikulum VALUES ('IKS108', 'Praktikum Sistem Informasi Manajemen');
-- INSERT INTO kurikulum VALUES ('IKG121', 'Praktikum Rekayasa Sistem Multimedia');
-- INSERT INTO kurikulum VALUES ('IKH126', 'Praktikum Perencanaan Kontinyuitas Bisnis');
-- INSERT INTO kurikulum VALUES ('IKG102', 'Praktikum Pengolahan Citra');
-- INSERT INTO kurikulum VALUES ('ISO101', 'Praktikum Pengelolaan Sistem Informasi');
-- INSERT INTO kurikulum VALUES ('IKH109', 'Praktikum Pengelolaan Keamanan Informasi');
-- INSERT INTO kurikulum VALUES ('IKH132', 'Praktikum Pengelolaan Jaringan Komputer');
-- INSERT INTO kurikulum VALUES ('IKP111', 'Praktikum Pemrograman Berbasis Web');
-- INSERT INTO kurikulum VALUES ('IKP102', 'Praktikum Pemrograman Berbasis Komponen');
-- INSERT INTO kurikulum VALUES ('IKL133', 'Praktikum Pemodelan Geometri');
-- INSERT INTO kurikulum VALUES ('IKH151', 'Praktikum Organisasi dan Arsitektur Komputer');
-- INSERT INTO kurikulum VALUES ('IKP103', 'Praktikum Mobile Programming');
-- INSERT INTO kurikulum VALUES ('IKS104', 'Praktikum Metode Berorientasi Objek');
-- INSERT INTO kurikulum VALUES ('IKD123', 'Praktikum Manajemen Data dan Informasi Lanjut');
-- INSERT INTO kurikulum VALUES ('IKD112', 'Praktikum Manajemen Data dan Informasi');
-- INSERT INTO kurikulum VALUES ('IKH112', 'Praktikum Keamanan Sistem Operasi');
-- INSERT INTO kurikulum VALUES ('IKH119', 'Praktikum Keamanan Operasional');
-- INSERT INTO kurikulum VALUES ('IKH110', 'Praktikum Keamanan Jaringan Komputer');
-- INSERT INTO kurikulum VALUES ('IKH123', 'Praktikum Keamanan Informasi');
-- INSERT INTO kurikulum VALUES ('IKH113', 'Praktikum Jaringan Komputer dan Keamanan');
-- INSERT INTO kurikulum VALUES ('IKG101', 'Praktikum Grafika Komputer');
-- INSERT INTO kurikulum VALUES ('IKH128', 'Praktikum Forensik Komputer dan Jaringan');
-- INSERT INTO kurikulum VALUES ('IKS126', 'Praktikum Desain Perangkat Lunak');
-- INSERT INTO kurikulum VALUES ('IKL135', 'Praktikum Dasar Pemrograman');
-- INSERT INTO kurikulum VALUES ('IKP113', 'Praktikum Bahasa Pemrograman');
-- INSERT INTO kurikulum VALUES ('ISM114', 'Praktikum Audit Sistem Informasi');
-- INSERT INTO kurikulum VALUES ('IKS123', 'Praktikum Analisis dan Pemodelan Perangkat Lunak');
-- INSERT INTO kurikulum VALUES ('IKH116', 'Praktikum Analisis dan Pemodelan Keamanan Informasi');
-- INSERT INTO kurikulum VALUES ('IIB205', 'Perilaku Organisasi');
-- INSERT INTO kurikulum VALUES ('IKH326', 'Perencanaan Kontinyuitas Bisnis');
-- INSERT INTO kurikulum VALUES ('IKB405', 'Penulisan ilmiah dan Laporan');
-- INSERT INTO kurikulum VALUES ('IKH342', 'Pengolahan Sinyal Digital');
-- INSERT INTO kurikulum VALUES ('IKG302', 'Pengolahan Citra');
-- INSERT INTO kurikulum VALUES ('ISL303', 'Pengetahuan Bisnis');
-- INSERT INTO kurikulum VALUES ('ISO301', 'Pengelolaan Sistem Informasi');
-- INSERT INTO kurikulum VALUES ('IKH329', 'Pengelolaan Keamanan Informasi');
-- INSERT INTO kurikulum VALUES ('IKH309', 'Pengelolaan Jaringan Komputer');
-- INSERT INTO kurikulum VALUES ('ISM313', 'Pengantar Audit Sistem Informasi');
-- INSERT INTO kurikulum VALUES ('IKP311', 'Pemrograman Berbasis Web');
-- INSERT INTO kurikulum VALUES ('IKP302', 'Pemrograman Berbasis Komponen');
-- INSERT INTO kurikulum VALUES ('IKL233', 'Pemodelan Geometri');
-- INSERT INTO kurikulum VALUES ('UKW400', 'Pancasila dan Kewarganegaraan');
-- INSERT INTO kurikulum VALUES ('UKW400', 'Pancasila dan Kewarganegaraan');
-- INSERT INTO kurikulum VALUES ('IKH351', 'Organisasi dan Arsitektur Komputer');
-- INSERT INTO kurikulum VALUES ('IKH316', 'Model dan Arsitektur Keamanan Informasi');
-- INSERT INTO kurikulum VALUES ('IKP303', 'Mobile Programming');
-- INSERT INTO kurikulum VALUES ('IKB406', 'Metodologi Penelitian');
-- INSERT INTO kurikulum VALUES ('IKS304', 'Metode Berorientasi Objek');
-- INSERT INTO kurikulum VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi');
-- INSERT INTO kurikulum VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut');
-- INSERT INTO kurikulum VALUES ('IKD312', 'Manajemen Data dan Informasi');
-- INSERT INTO kurikulum VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak');
-- INSERT INTO kurikulum VALUES ('IKB250', 'Kuliah Kerja Profesi');
-- INSERT INTO kurikulum VALUES ('UKT101', 'Kuliah Kerja Lapangan');
-- INSERT INTO kurikulum VALUES ('IKB206', 'Kreativitas dan Inovasi');
-- INSERT INTO kurikulum VALUES ('IKB411', 'Konsep Teknologi Informasi dan Keamanan');
-- INSERT INTO kurikulum VALUES ('IKH312', 'Keamanan Sistem Operasi');
-- INSERT INTO kurikulum VALUES ('IKH324', 'Keamanan Pengembangan Aplikasi');
-- INSERT INTO kurikulum VALUES ('IKH319', 'Keamanan Operasional');
-- INSERT INTO kurikulum VALUES ('IKH323', 'Keamanan Informasi');
-- INSERT INTO kurikulum VALUES ('IKH327', 'Keamanan Fisik');
-- INSERT INTO kurikulum VALUES ('IUM314', 'Kalkulus');
-- INSERT INTO kurikulum VALUES ('IKH313', 'Jaringan Komputer dan Keamanan');
-- INSERT INTO kurikulum VALUES ('IKS328', 'ITSM (Information Technology Service Management)');
-- INSERT INTO kurikulum VALUES ('UBA402', 'Internasionalisasi');
-- INSERT INTO kurikulum VALUES ('IKS301', 'Interaksi Manusia dan Komputer');
-- INSERT INTO kurikulum VALUES ('IKG401', 'Grafika Komputer');
-- INSERT INTO kurikulum VALUES ('IKH328', 'Forensik Komputer dan Jaringan');
-- INSERT INTO kurikulum VALUES ('ISM403', 'Etika Agama Profesionalisme dan Legal');
-- INSERT INTO kurikulum VALUES ('ISM221', 'Ekonomi Informasi');
-- INSERT INTO kurikulum VALUES ('IKS327', 'Desain Perangkat Lunak');
-- INSERT INTO kurikulum VALUES ('IKL343', 'Desain dan Analisis Algoritma');
-- INSERT INTO kurikulum VALUES ('IKL335', 'Dasar Pemrograman');
-- INSERT INTO kurikulum VALUES ('IKP213', 'Bahasa Pemrograman');
-- INSERT INTO kurikulum VALUES ('ISM314', 'Audit Sistem Informasi');
-- INSERT INTO kurikulum VALUES ('IKS326', 'Arsitektur Enterprise');
-- INSERT INTO kurikulum VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak');
-- INSERT INTO kurikulum VALUES ('ISL304', 'Analisa Proses Bisnis');

