CREATE TABLE termgenap (
  kode TEXT(6) NOT NULL,
  kuliah TEXT NOT NULL,
  semester TEXT(1) NOT NULL
);

INSERT INTO termgenap VALUES ('ISL304', 'Analisa Proses Bisnis', '4');
INSERT INTO termgenap VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak', '3');
INSERT INTO termgenap VALUES ('ISM314', 'Audit Sistem Informasi', 'P');
INSERT INTO termgenap VALUES ('ISM314', 'Audit Sistem Informasi', '6');
INSERT INTO termgenap VALUES ('IKL335', 'Dasar Pemrograman', '1');
INSERT INTO termgenap VALUES ('IKS327', 'Desain Perangkat Lunak', '4');
INSERT INTO termgenap VALUES ('IKH328', 'Forensik Komputer dan Jaringan', '4');
INSERT INTO termgenap VALUES ('IKG401', 'Grafika Komputer', '4');
INSERT INTO termgenap VALUES ('IKH313', 'Jaringan Komputer dan Keamanan', '2');
INSERT INTO termgenap VALUES ('IKH323', 'Keamanan Informasi', '7');
INSERT INTO termgenap VALUES ('IKH323', 'Keamanan Informasi', '3');
INSERT INTO termgenap VALUES ('IKD312', 'Manajemen Data dan Informasi', '3');
INSERT INTO termgenap VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi', '4');
INSERT INTO termgenap VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi', '4');
INSERT INTO termgenap VALUES ('IKS304', 'Metode Berorientasi Objek', '3');
INSERT INTO termgenap VALUES ('IKS304', 'Metode Berorientasi Objek', 'P');
INSERT INTO termgenap VALUES ('IKH316', 'Model dan Arsitektur Keamanan Informasi', '5');
INSERT INTO termgenap VALUES ('IKL233', 'Pemodelan Geometri', '5');
INSERT INTO termgenap VALUES ('ISM313', 'Pengantar Audit Sistem Informasi', '5');
INSERT INTO termgenap VALUES ('IKH329', 'Pengelolaan Keamanan Informasi', '4');
INSERT INTO termgenap VALUES ('ISO301', 'Pengelolaan Sistem Informasi', '4');
INSERT INTO termgenap VALUES ('IKH326', 'Perencanaan Kontinyuitas Bisnis', 'P');
INSERT INTO termgenap VALUES ('IKH326', 'Perencanaan Kontinyuitas Bisnis', '5');
INSERT INTO termgenap VALUES ('IKG321', 'Rekayasa Sistem Multimedia', 'P');
INSERT INTO termgenap VALUES ('IKG321', 'Rekayasa Sistem Multimedia', '6');
INSERT INTO termgenap VALUES ('IKS308', 'Sistem Informasi Manajemen', '3');
INSERT INTO termgenap VALUES ('IKH311', 'Sistem Operasi', '2');
INSERT INTO termgenap VALUES ('IKH314', 'Sistem Pengendalian Akses', 'P');
INSERT INTO termgenap VALUES ('IKH314', 'Sistem Pengendalian Akses', '3');
INSERT INTO termgenap VALUES ('IUM461', 'Struktur Diskrit I', '1');
INSERT INTO termgenap VALUES ('IKH318', 'Verifikasi dan Validasi  Keamanan Informasi', '6');
INSERT INTO termgenap VALUES ('IKS318', 'Verifikasi dan Validasi  Perangkat Lunak', '5');
INSERT INTO termgenap VALUES ('IKS326', 'Arsitektur Enterprise', '6');
INSERT INTO termgenap VALUES ('IKP213', 'Bahasa Pemrograman', '7');
INSERT INTO termgenap VALUES ('ISA301', 'Bisnis Berbasis Internet', 'P');
INSERT INTO termgenap VALUES ('ISL305', 'Business Intelligence', 'P');
INSERT INTO termgenap VALUES ('IKP333', 'Cloud Computing', 'P');
INSERT INTO termgenap VALUES ('ISD301', 'Data Warehouse', 'P');
INSERT INTO termgenap VALUES ('IKL343', 'Desain dan Analisis Algoritma', '6');
INSERT INTO termgenap VALUES ('ISM221', 'Ekonomi Informasi', '4');
INSERT INTO termgenap VALUES ('ISM221', 'Ekonomi Informasi', '5');
INSERT INTO termgenap VALUES ('ISM403', 'Etika, Agama, Profesionalisme dan Legal', '6');
INSERT INTO termgenap VALUES ('ISD312', 'Information Retrieval', 'P');
INSERT INTO termgenap VALUES ('IKS301', 'Interaksi Manusia dan Komputer', '3');
INSERT INTO termgenap VALUES ('IKS301', 'Interaksi Manusia dan Komputer', '5');
INSERT INTO termgenap VALUES ('UBA402', 'Internasionalisasi', '1');
INSERT INTO termgenap VALUES ('IKS328', 'ITSM (Information Technology Service Management)', '7');
INSERT INTO termgenap VALUES ('IUM314', 'Kalkulus', '3');
INSERT INTO termgenap VALUES ('IKH327', 'Keamanan Fisik', '6');
INSERT INTO termgenap VALUES ('IKH319', 'Keamanan Operasional', '5');
INSERT INTO termgenap VALUES ('IKH324', 'Keamanan Pengembangan Aplikasi', '7');
INSERT INTO termgenap VALUES ('IKH312', 'Keamanan Sistem Operasi', '3');
INSERT INTO termgenap VALUES ('IKA301', 'Kecerdasan Buatan', 'P');
INSERT INTO termgenap VALUES ('ISL302', 'Komunikasi Bisnis dan Teknis', 'P');
INSERT INTO termgenap VALUES ('IKB411', 'Konsep Teknologi Informasi dan Keamanan', '1');
INSERT INTO termgenap VALUES ('IKB206', 'Kreativitas dan Inovasi', '5');
INSERT INTO termgenap VALUES ('UKT101', 'Kuliah Kerja Lapangan', '2');
INSERT INTO termgenap VALUES ('IKB250', 'Kuliah Kerja Profesi', '7');
INSERT INTO termgenap VALUES ('UKT300', 'KUM-ITT', 'P');
INSERT INTO termgenap VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak', '6');
INSERT INTO termgenap VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak', 'P');
INSERT INTO termgenap VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut', '5');
INSERT INTO termgenap VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut', '7');
INSERT INTO termgenap VALUES ('ISM317', 'Manajemen Dokumen', 'P');
INSERT INTO termgenap VALUES ('ISM315', 'Manajemen Keuangan', 'P');
INSERT INTO termgenap VALUES ('ISM316', 'Manajemen Pemasaran IT', 'P');
INSERT INTO termgenap VALUES ('ISM312', 'Manajemen Pengetahuan', 'P');
INSERT INTO termgenap VALUES ('ISM202', 'Manajemen Pengetahuan', 'P');
INSERT INTO termgenap VALUES ('IKB406', 'Metodologi Penelitian', '5');
INSERT INTO termgenap VALUES ('IKP303', 'Mobile Programming', '5');
INSERT INTO termgenap VALUES ('IKP303', 'Mobile Programming', 'P');
INSERT INTO termgenap VALUES ('IKH351', 'Organisasi dan Arsitektur Komputer', '1');
INSERT INTO termgenap VALUES ('UKW400', 'Pancasila dan Kewarganegaraan', '4');
INSERT INTO termgenap VALUES ('IKP302', 'Pemrograman Berbasis Komponen', '4');
INSERT INTO termgenap VALUES ('IKP311', 'Pemrograman Berbasis Web', '4');
INSERT INTO termgenap VALUES ('IKP311', 'Pemrograman Berbasis Web', 'P');
INSERT INTO termgenap VALUES ('IKH309', 'Pengelolaan Jaringan Komputer', '3');
INSERT INTO termgenap VALUES ('IKH309', 'Pengelolaan Jaringan Komputer', '7');
INSERT INTO termgenap VALUES ('ISL303', 'Pengetahuan Bisnis', '3');
INSERT INTO termgenap VALUES ('IKG302', 'Pengolahan Citra', '5');
INSERT INTO termgenap VALUES ('IKH342', 'Pengolahan Sinyal Digital', '4');
INSERT INTO termgenap VALUES ('IKB405', 'Penulisan Ilmiah dan Laporan', '2');
INSERT INTO termgenap VALUES ('IIB205', 'Perilaku Organisasi', '3');
INSERT INTO termgenap VALUES ('IKH116', 'Praktikum Analisis dan Pemodelan Keamanan Informasi', '5');
INSERT INTO termgenap VALUES ('IKS123', 'Praktikum Analisis dan Pemodelan Perangkat Lunak', '3');
INSERT INTO termgenap VALUES ('ISM114', 'Praktikum Audit Sistem Informasi', '6');
INSERT INTO termgenap VALUES ('IKP113', 'Praktikum Bahasa Pemrograman', '7');
INSERT INTO termgenap VALUES ('IKL135', 'Praktikum Dasar Pemrograman', '1');
INSERT INTO termgenap VALUES ('IKS126', 'Praktikum Desain Perangkat Lunak', '4');
INSERT INTO termgenap VALUES ('IKH128', 'Praktikum Forensik Komputer dan Jaringan', '4');
INSERT INTO termgenap VALUES ('IKG101', 'Praktikum Grafika Komputer', '4');
INSERT INTO termgenap VALUES ('IKH113', 'Praktikum Jaringan Komputer dan Keamanan', '2');
INSERT INTO termgenap VALUES ('IKH123', 'Praktikum Keamanan Informasi', '3');
INSERT INTO termgenap VALUES ('IKH110', 'Praktikum Keamanan Jaringan Komputer', '4');
INSERT INTO termgenap VALUES ('IKH119', 'Praktikum Keamanan Operasional', '5');
INSERT INTO termgenap VALUES ('IKH112', 'Praktikum Keamanan Sistem Operasi', '3');
INSERT INTO termgenap VALUES ('IKD112', 'Praktikum Manajemen Data dan Informasi', '3');
INSERT INTO termgenap VALUES ('IKD123', 'Praktikum Manajemen Data dan Informasi Lanjut', '5');
INSERT INTO termgenap VALUES ('IKD123', 'Praktikum Manajemen Data dan Informasi Lanjut', '7');
INSERT INTO termgenap VALUES ('IKS104', 'Praktikum Metode Berorientasi Objek', '3');
INSERT INTO termgenap VALUES ('IKP103', 'Praktikum Mobile Programming', '5');
INSERT INTO termgenap VALUES ('IKH151', 'Praktikum Organisasi dan Arsitektur Komputer', '1');
INSERT INTO termgenap VALUES ('IKL133', 'Praktikum Pemodelan Geometri', '5');
INSERT INTO termgenap VALUES ('IKP102', 'Praktikum Pemrograman Berbasis Komponen', '4');
INSERT INTO termgenap VALUES ('IKP111', 'Praktikum Pemrograman Berbasis Web', '4');
INSERT INTO termgenap VALUES ('IKH132', 'Praktikum Pengelolaan Jaringan Komputer', '7');
INSERT INTO termgenap VALUES ('IKH109', 'Praktikum Pengelolaan Keamanan Informasi', '4');
INSERT INTO termgenap VALUES ('ISO101', 'Praktikum Pengelolaan Sistem Informasi', '4');
INSERT INTO termgenap VALUES ('IKG102', 'Praktikum Pengolahan Citra', '5');
INSERT INTO termgenap VALUES ('IKH126', 'Praktikum Perencanaan Kontinyuitas Bisnis', '5');
INSERT INTO termgenap VALUES ('IKG121', 'Praktikum Rekayasa Sistem Multimedia', '6');
INSERT INTO termgenap VALUES ('IKS108', 'Praktikum Sistem Informasi Manajemen', '3');
INSERT INTO termgenap VALUES ('IKH111', 'Praktikum Sistem Operasi', '2');
INSERT INTO termgenap VALUES ('IKH114', 'Praktikum Sistem Pengendalian Akses', '3');
INSERT INTO termgenap VALUES ('IKL141', 'Praktikum Struktur Data dan Algoritma', '2');
INSERT INTO termgenap VALUES ('IKH118', 'Praktikum Verifikasi dan Validasi Keamanan Informasi', '6');
INSERT INTO termgenap VALUES ('IKS118', 'Praktikum Verifikasi dan Validasi Perangkat Lunak', '5');
INSERT INTO termgenap VALUES ('ISM404', 'Proyek Rekayasa', '6');
INSERT INTO termgenap VALUES ('ISD305', 'Rekayasa Data dan Pengetahuan', 'P');
INSERT INTO termgenap VALUES ('IKG304', 'Seni Animasi', 'P');
INSERT INTO termgenap VALUES ('IKG311', 'Sistem Informasi Geografi', 'P');
INSERT INTO termgenap VALUES ('IKH310', 'Sistem Keamanan Jaringan', '4');
INSERT INTO termgenap VALUES ('IKH331', 'Sistem Terdistribusi', '5');
INSERT INTO termgenap VALUES ('IKL341', 'Struktur Data dan Algoritma', '2');
INSERT INTO termgenap VALUES ('IUM263', 'Struktur Diskrit II', '3');
INSERT INTO termgenap VALUES ('IKS413', 'Technopreneurship', '2');
INSERT INTO termgenap VALUES ('ISD314', 'Teknik Data Mining', 'P');
INSERT INTO termgenap VALUES ('PDU212', 'Teori Warna', '5');
INSERT INTO termgenap VALUES ('IKB450', 'Tugas Akhir I', '7');
INSERT INTO termgenap VALUES ('IKB451', 'Tugas Akhir II', '8');
INSERT INTO termgenap VALUES ('IKS319', 'Verifikasi dan Validasi Sistem Informasi', '5');
INSERT INTO termgenap VALUES ('ISD313', 'Virtualisasi', 'P');
