DROP TABLE IF EXISTS kurop;

CREATE TABLE kurop (
  kode CHAR(6),
  nama VARCHAR(60)
);

BEGIN;
INSERT INTO kurop VALUES ('IKS326', 'Arsitektur Enterprise');
INSERT INTO kurop VALUES ('IKL343', 'Desain dan Analisis Algoritma');
INSERT INTO kurop VALUES ('ISM221', 'Ekonomi Informasi');
INSERT INTO kurop VALUES ('ISM403', 'Etika Agama Profesionalisme dan Legal');
INSERT INTO kurop VALUES ('IKH327', 'Keamanan Fisik');
INSERT INTO kurop VALUES ('UKT101', 'Kuliah Kerja Lapangan');
INSERT INTO kurop VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak');
INSERT INTO kurop VALUES ('UKW400', 'Pancasila dan Kewarganegaraan');
INSERT INTO kurop VALUES ('IKP302', 'Pemrograman Berbasis Komponen');
INSERT INTO kurop VALUES ('IKP311', 'Pemrograman Berbasis Web');
INSERT INTO kurop VALUES ('IKH342', 'Pengolahan Sinyal Digital');
INSERT INTO kurop VALUES ('IKB405', 'Penulisan Ilmiah dan Laporan');
INSERT INTO kurop VALUES ('ISM114', 'Praktikum Audit Sistem Informasi');
INSERT INTO kurop VALUES ('IKS126', 'Praktikum Desain Perangkat Lunak');
INSERT INTO kurop VALUES ('IKH128', 'Praktikum Forensik Komputer dan Jaringan');
INSERT INTO kurop VALUES ('IKG101', 'Praktikum Grafika Komputer');
INSERT INTO kurop VALUES ('IKH113', 'Praktikum Jaringan Komputer dan Keamanan');
INSERT INTO kurop VALUES ('IKH110', 'Praktikum Keamanan Jaringan Komputer');
INSERT INTO kurop VALUES ('IKP102', 'Praktikum Pemrograman Berbasis Komponen');
INSERT INTO kurop VALUES ('IKP111', 'Praktikum Pemrograman Berbasis Web');
INSERT INTO kurop VALUES ('IKH109', 'Praktikum Pengelolaan Keamanan Informasi');
INSERT INTO kurop VALUES ('ISO101', 'Praktikum Pengelolaan Sistem Informasi');
INSERT INTO kurop VALUES ('IKG121', 'Praktikum Rekayasa Sistem Multimedia');
INSERT INTO kurop VALUES ('IKH111', 'Praktikum Sistem Operasi');
INSERT INTO kurop VALUES ('IKL141', 'Praktikum Struktur Data dan Algoritma');
INSERT INTO kurop VALUES ('IKH118', 'Praktikum Verifikasi dan Validasi Keamanan Informasi');
INSERT INTO kurop VALUES ('ISM404', 'Proyek Rekayasa');
INSERT INTO kurop VALUES ('IKH310', 'Sistem Keamanan Jaringan');
INSERT INTO kurop VALUES ('IKL341', 'Struktur Data dan Algoritma');
INSERT INTO kurop VALUES ('IKS413', 'Technopreneurship');
INSERT INTO kurop VALUES ('IKP213', 'Bahasa Pemrograman');
INSERT INTO kurop VALUES ('IKL335', 'Dasar Pemrograman');
INSERT INTO kurop VALUES ('IKS301', 'Interaksi Manusia dan Komputer');
INSERT INTO kurop VALUES ('UBA402', 'Internasionalisasi');
INSERT INTO kurop VALUES ('IKS328', 'ITSM (Information Technology Service Management)');
INSERT INTO kurop VALUES ('IUM314', 'Kalkulus');
INSERT INTO kurop VALUES ('IKH319', 'Keamanan Operasional');
INSERT INTO kurop VALUES ('IKH324', 'Keamanan Pengembangan Aplikasi');
INSERT INTO kurop VALUES ('IKH312', 'Keamanan Sistem Operasi');
INSERT INTO kurop VALUES ('IKB411', 'Konsep Teknologi Informasi dan Keamanan');
INSERT INTO kurop VALUES ('IKB206', 'Kreativitas dan Innovasi');
INSERT INTO kurop VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut');
INSERT INTO kurop VALUES ('IKB406', 'Metodologi Penelitian');
INSERT INTO kurop VALUES ('IKP303', 'Mobile Programming');
INSERT INTO kurop VALUES ('IKH351', 'Organisasi dan Arsitektur Komputer');
INSERT INTO kurop VALUES ('IKH309', 'Pengelolaan Jaringan Komputer');
INSERT INTO kurop VALUES ('ISL303', 'Pengetahuan Bisnis');
INSERT INTO kurop VALUES ('IKG302', 'Pengolahan Citra');
INSERT INTO kurop VALUES ('IIB205', 'Perilaku Organisasi');
INSERT INTO kurop VALUES ('IKS123', 'Praktikum Analisis dan Pemodelan Perangkat Lunak');
INSERT INTO kurop VALUES ('IKP113', 'Praktikum Bahasa Pemrograman');
INSERT INTO kurop VALUES ('IKL135', 'Praktikum Dasar Pemrograman');
INSERT INTO kurop VALUES ('IKH123', 'Praktikum Keamanan Informasi');
INSERT INTO kurop VALUES ('IKH119', 'Praktikum Keamanan Operasional');
INSERT INTO kurop VALUES ('IKH112', 'Praktikum Keamanan Sistem Operasi');
INSERT INTO kurop VALUES ('IKD112', 'Praktikum Manajemen Data dan Informasi');
INSERT INTO kurop VALUES ('IKD123', 'Praktikum Manajemen Data dan Informasi Lanjut');
INSERT INTO kurop VALUES ('IKS104', 'Praktikum Metode Berorientasi Objek');
INSERT INTO kurop VALUES ('IKP103', 'Praktikum Mobile Programming');
INSERT INTO kurop VALUES ('IKH116', 'Praktikum Model dan Arsitektur Keamanan Informasi');
INSERT INTO kurop VALUES ('IKH151', 'Praktikum Organisasi dan Arsitektur Komputer');
INSERT INTO kurop VALUES ('IKL133', 'Praktikum Pemodelan Geometri');
INSERT INTO kurop VALUES ('IKH132', 'Praktikum Pengelolaan Jaringan Komputer');
INSERT INTO kurop VALUES ('IKG102', 'Praktikum Pengolahan Citra');
INSERT INTO kurop VALUES ('IKH126', 'Praktikum Perencanaan Kontinyuitas Bisnis');
INSERT INTO kurop VALUES ('IKS108', 'Praktikum Sistem Informasi Manajemen');
INSERT INTO kurop VALUES ('IKH114', 'Praktikum Sistem Pengendalian Akses');
INSERT INTO kurop VALUES ('IKS118', 'Praktikum Verifikasi dan Validasi Perangkat Lunak');
INSERT INTO kurop VALUES ('IKH331', 'Sistem Terdistribusi');
INSERT INTO kurop VALUES ('IUM263', 'Struktur Diskrit II');
INSERT INTO kurop VALUES ('PDU212', 'Teori Warna');
INSERT INTO kurop VALUES ('IKS319', 'Verifikasi dan Validasi Sistem Informasi');
END;

