CREATE TABLE IF NOT EXISTS indukkonsentrasi (
  kode TEXT PRIMARY KEY,
  nama TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS indukkuliah (
  kode TEXT(6) PRIMARY KEY,
  kuliah TEXT NOT NULL,
  konsentrasi TEXT,
  semester TEXT(2)
);

INSERT INTO indukkuliah VALUES ('IEB232', 'Teknik Komunikasi Data', '5');
INSERT INTO indukkuliah VALUES ('IFI301', 'Fisika I', '2');
INSERT INTO indukkuliah VALUES ('IFI302', 'Fisika II', '3');
INSERT INTO indukkuliah VALUES ('IIB205', 'Perilaku Organisasi', '7');
INSERT INTO indukkuliah VALUES ('IIS201', 'Penelitian Operasiaonal', '4');
INSERT INTO indukkuliah VALUES ('IKA301', 'Kecerdasan Buatan', '6');
INSERT INTO indukkuliah VALUES ('IKA312', 'Sistem Jaringan Syaraf', '7');
INSERT INTO indukkuliah VALUES ('IKA321', 'Komputasi Bergerak', '0');
INSERT INTO indukkuliah VALUES ('IKB205', 'Metodologi Penelitian dan Penulisan Ilmiah', '0');
INSERT INTO indukkuliah VALUES ('IKB206', 'Kreativitas dan innovasi', '0');
INSERT INTO indukkuliah VALUES ('IKB250', 'Kuliah Kerja Profesi', '0');
INSERT INTO indukkuliah VALUES ('IKB405', 'Penulisan Ilmiah dan Laporan', '0');
INSERT INTO indukkuliah VALUES ('IKB406', 'Metodologi Penelitian', '0');
INSERT INTO indukkuliah VALUES ('IKB411', 'Konsep Teknologi Informasi dan Keamanan', '0');
INSERT INTO indukkuliah VALUES ('IKB450', 'Tugas Akhir I', '0');
INSERT INTO indukkuliah VALUES ('IKB451', 'Tugas Akhir II', '0');
INSERT INTO indukkuliah VALUES ('IKD112', 'Praktikum Manajemen Data dan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKD123', 'Praktikum Manajemen Data dan Informasi Lanjut', '0');
INSERT INTO indukkuliah VALUES ('IKD312', 'Manajemen Data dan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKD313', 'Manajemen Data dan Informasi Lanjut', '0');
INSERT INTO indukkuliah VALUES ('IKG101', 'Praktikum Grafika Komputer', '0');
INSERT INTO indukkuliah VALUES ('IKG102', 'Praktikum Pengolahan Citra', '0');
INSERT INTO indukkuliah VALUES ('IKG121', 'Praktikum Rekayasa Sistem Multimedia', '0');
INSERT INTO indukkuliah VALUES ('IKG301', 'Grafika Komputer', '0');
INSERT INTO indukkuliah VALUES ('IKG302', 'Pengolahan Citra', '7');
INSERT INTO indukkuliah VALUES ('IKG304', 'Seni Animasi', '0');
INSERT INTO indukkuliah VALUES ('IKG311', 'Sistem Informasi Geografi', '0');
INSERT INTO indukkuliah VALUES ('IKG321', 'Rekayasa Sistem Multimedia', '6');
INSERT INTO indukkuliah VALUES ('IKG402', 'Grafika Komputer', '0');
INSERT INTO indukkuliah VALUES ('IKH109', 'Praktikum Pengelolaan Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH110', 'Praktikum Keamanan Jaringan Komputer', '0');
INSERT INTO indukkuliah VALUES ('IKH111', 'Praktikum Sistem Operasi', '0');
INSERT INTO indukkuliah VALUES ('IKH112', 'Praktikum Keamanan Sistem Operasi', '0');
INSERT INTO indukkuliah VALUES ('IKH113', 'Praktikum Jaringan Komputer dan Keamanan', '0');
INSERT INTO indukkuliah VALUES ('IKH114', 'Praktikum Sistem Pengendalian Akses', '0');
INSERT INTO indukkuliah VALUES ('IKH116', 'Praktikum Model dan Arsitektur Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH117', 'Praktikum Desain Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH118', 'Prakt. Verifikasi dan Validasi Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH119', 'Praktikum Keamanan Operasional', '0');
INSERT INTO indukkuliah VALUES ('IKH123', 'Praktikum Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH126', 'Praktikum Perencanaan Kontinyuitas Bisnis', '0');
INSERT INTO indukkuliah VALUES ('IKH128', 'Praktikum Forensik Komputer dan Jaringan', '0');
INSERT INTO indukkuliah VALUES ('IKH132', 'Praktikum Pengelolaan Jaringan Komputer', '0');
INSERT INTO indukkuliah VALUES ('IKH151', 'Prak. Organisasi dan Arsitektur Komputer', '0');
INSERT INTO indukkuliah VALUES ('IKH203', 'Arsitektur Komputer', '0');
INSERT INTO indukkuliah VALUES ('IKH300', 'Pengantar Sistim Digital', '1');
INSERT INTO indukkuliah VALUES ('IKH303', 'Arsitektur Komputer', '7');
INSERT INTO indukkuliah VALUES ('IKH306', 'Pemrograman Jaringan', '7');
INSERT INTO indukkuliah VALUES ('IKH309', 'Pengelolaan Jaringan Komputer', '0');
INSERT INTO indukkuliah VALUES ('IKH310', 'Sistem Keamanan Jaringan', '0');
INSERT INTO indukkuliah VALUES ('IKH311', 'Sistem Operasi', '5');
INSERT INTO indukkuliah VALUES ('IKH312', 'Keamanan Sistem Operasi', '0');
INSERT INTO indukkuliah VALUES ('IKH313', 'Jaringan Komputer dan Keamanan', '0');
INSERT INTO indukkuliah VALUES ('IKH314', 'Sistem Pengendalian Akses', '0');
INSERT INTO indukkuliah VALUES ('IKH316', 'Model dan Arsitektur Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH317', 'Desain Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH318', 'Verifikasi dan Validasi Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH319', 'Keamanan Operasional', '0');
INSERT INTO indukkuliah VALUES ('IKH321', 'Sistem Keamanan Komputer', '6');
INSERT INTO indukkuliah VALUES ('IKH323', 'Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH324', 'Keamanan Pengembangan Aplikasi', '0');
INSERT INTO indukkuliah VALUES ('IKH326', 'Perencanaan Kontinyuitas Bisnis', '0');
INSERT INTO indukkuliah VALUES ('IKH327', 'Keamanan Fisisk', '0');
INSERT INTO indukkuliah VALUES ('IKH328', 'Forensik Komputer dan Jaringan', '0');
INSERT INTO indukkuliah VALUES ('IKH329', 'Pengelolaan Keamanan Informasi', '0');
INSERT INTO indukkuliah VALUES ('IKH330', 'Bahasa Rakitan', '0');
INSERT INTO indukkuliah VALUES ('IKH331', 'Sistem Terdistribusi', '0');
INSERT INTO indukkuliah VALUES ('IKH342', 'Pengolahan Sinyal Dijital', '0');
INSERT INTO indukkuliah VALUES ('IKH351', 'Organisasi dan Arsitektur Komputer', '0');
INSERT INTO indukkuliah VALUES ('IKL133', 'Praktikum Pemodelan Geometri', '0');
INSERT INTO indukkuliah VALUES ('IKL135', 'Praktikum Dasar Pemrograman', '0');
INSERT INTO indukkuliah VALUES ('IKL141', 'Prak Struktur Data dan Algorithma', '0');
INSERT INTO indukkuliah VALUES ('IKL232', 'Model Dan Simulasi', '5');
INSERT INTO indukkuliah VALUES ('IKL233', 'Pemodelan Geometri', '0');
INSERT INTO indukkuliah VALUES ('IKL335', 'Dasar Pemrograman', '0');
INSERT INTO indukkuliah VALUES ('IKL341', 'Struktur Data & Algoritma', '3');
INSERT INTO indukkuliah VALUES ('IKL343', 'Disain & Analisa Algoritma (MPM)', '0');
INSERT INTO indukkuliah VALUES ('IKP102', 'Praktikum Pemrograman Berbasis Komponen', '0');
INSERT INTO indukkuliah VALUES ('IKP103', 'Praktikum Mobile Programming', '0');
INSERT INTO indukkuliah VALUES ('IKP111', 'Praktikum Pemrograman Berbasis Web', '0');
INSERT INTO indukkuliah VALUES ('IKP113', 'Praktikum Bahasa Pemrograman', '0');
INSERT INTO indukkuliah VALUES ('IKP213', 'Bahasa Pemrograman', '0');
INSERT INTO indukkuliah VALUES ('IKP301', 'Desain dan Implementasi Program', '0');
INSERT INTO indukkuliah VALUES ('IKP302', 'Pemprog Berbasis Komponen', '0');
INSERT INTO indukkuliah VALUES ('IKP303', 'Mobile Programming', '0');
INSERT INTO indukkuliah VALUES ('IKP311', 'Pemrograman Berbasis Web', '0');
INSERT INTO indukkuliah VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak', '0');
INSERT INTO indukkuliah VALUES ('IKP333', 'Cloud Computing', '0');
INSERT INTO indukkuliah VALUES ('IKS104', 'Praktikum Metode Berorientasi Objek', '0');
INSERT INTO indukkuliah VALUES ('IKS118', 'Praktikum Verifikasi dan Validasi Perangkat Lunak', '0');
INSERT INTO indukkuliah VALUES ('IKS123', 'Praktikum Analisis dan Pemodelan Perangkat Lunak', '0');
INSERT INTO indukkuliah VALUES ('IKS126', 'Praktikum Desain Perangkat Lunak', '0');
INSERT INTO indukkuliah VALUES ('IKS201', 'Arsitektur Perangkat Lunak', '0');
INSERT INTO indukkuliah VALUES ('IKS212', 'Computer Aided Software Engineering', '7');
INSERT INTO indukkuliah VALUES ('IKS213', 'Kewirausahaan Telematika', '0');
INSERT INTO indukkuliah VALUES ('IKS301', 'Interaksi Manusia Dan Komputer', '4');
INSERT INTO indukkuliah VALUES ('IKS302', 'Sistem Informasi', '6');
INSERT INTO indukkuliah VALUES ('IKS304', 'Metode Berorientasi Obyek', '7');
INSERT INTO indukkuliah VALUES ('IKS308', 'Sistem Informasi Manajemen', '0');
INSERT INTO indukkuliah VALUES ('IKS318', 'Verifikasi dan Validasi Perangkat Lunak', '0');
INSERT INTO indukkuliah VALUES ('IKS323', 'Analisis dan Pemodelan Perangkat Lunak', '0');
INSERT INTO indukkuliah VALUES ('IKS327', 'Desain Perangkat Lunak', '0');
INSERT INTO indukkuliah VALUES ('IKS413', 'Technopreneurship', '0');
INSERT INTO indukkuliah VALUES ('ISD305', 'Rekayasa Data dan Pengetahuan', '0');
INSERT INTO indukkuliah VALUES ('ISD312', 'Information Retrieval', '0');
INSERT INTO indukkuliah VALUES ('ISD313', 'Virtualisasi', '0');
INSERT INTO indukkuliah VALUES ('ISD314', 'Teknik Data Mining', '0');
INSERT INTO indukkuliah VALUES ('ISM221', 'Ekonomi Informasi', '0');
INSERT INTO indukkuliah VALUES ('ISM302', 'Manajemen Konfigurasi', '0');
INSERT INTO indukkuliah VALUES ('ISM303', 'Komunikasi Interpersonal & Etika Profesi', '0');
INSERT INTO indukkuliah VALUES ('ISM312', 'Manajemen Pengetahuan', '0');
INSERT INTO indukkuliah VALUES ('ISM314', 'Audit Sistem Informasi', '0');
INSERT INTO indukkuliah VALUES ('ISM317', 'Manajemen Dokumen', '0');
INSERT INTO indukkuliah VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi', '0');
INSERT INTO indukkuliah VALUES ('ISM403', 'Etika, Agama, Profesionalisme, dan Legal', '0');
INSERT INTO indukkuliah VALUES ('ISM404', 'Proyek Rekayasa', '0');
INSERT INTO indukkuliah VALUES ('IUM263', 'Struktur Diskrit II', '0');
INSERT INTO indukkuliah VALUES ('IUM314', 'Kalkulus', '0');
INSERT INTO indukkuliah VALUES ('IUM331', 'Kalkulus I', '1');
INSERT INTO indukkuliah VALUES ('IUM332', 'Kalkulus II', '2');
INSERT INTO indukkuliah VALUES ('IUM333', 'Kalkulus Lanjut', '3');
INSERT INTO indukkuliah VALUES ('IUM341', 'Aljabar Linier', '3');
INSERT INTO indukkuliah VALUES ('IUM351', 'Statistik Dasar', '4');
INSERT INTO indukkuliah VALUES ('IUM461', 'Struktur Diskrit I', '0');
INSERT INTO indukkuliah VALUES ('PDU212', 'Teori Warna', '0');
INSERT INTO indukkuliah VALUES ('PMA331', 'Kalkulus I', '1');
INSERT INTO indukkuliah VALUES ('PMA332', 'Kalkulus II', '2');
INSERT INTO indukkuliah VALUES ('UAG201', 'Pendidikan Agama Islam', '3');
INSERT INTO indukkuliah VALUES ('UAG202', 'Pendidikan Agama Kristen', '3');
INSERT INTO indukkuliah VALUES ('UAG203', 'Pendidikan Agama Katolik', '3');
INSERT INTO indukkuliah VALUES ('UAG204', 'Pendidikan Agama Budha', '3');
INSERT INTO indukkuliah VALUES ('UAG205', 'Pendidikan Agama Hindu', '3');
INSERT INTO indukkuliah VALUES ('UBA201', 'Bahasa Inggris I', '1');
INSERT INTO indukkuliah VALUES ('UBA202', 'Bahasa Inggris II', '2');
INSERT INTO indukkuliah VALUES ('UBA402', 'Internasionalisasi', '0');
INSERT INTO indukkuliah VALUES ('UBN200', 'Bahasa Indonesia', '2');
INSERT INTO indukkuliah VALUES ('UKD200', 'Keadilan, Demokrasi & HAM', '7');
INSERT INTO indukkuliah VALUES ('UKT101', 'Kuliah Kerja Lapangan', '0');
INSERT INTO indukkuliah VALUES ('UKT200', 'Kuliah Usaha Mandiri Ilmu Teknik Terapan', '7');
INSERT INTO indukkuliah VALUES ('UKT300', 'Kuliah Usaha Mandiri Ilmu Teknik Terapan', '7');
INSERT INTO indukkuliah VALUES ('UKW400', 'Pancasila dan Kewarganegaraan', '0');
INSERT INTO indukkuliah VALUES ('UPA200', 'Pendidikan Pancasila', '3');

