INSERT INTO offerred VALUES ('IKL335', 'Dasar Pemrograman');
INSERT INTO offerred VALUES ('IKS327', 'Desain Perangkat Lunak');
INSERT INTO offerred VALUES ('IKL343', 'Disain dan Analisa Algoritma (MPM)');
INSERT INTO offerred VALUES ('ISM221', 'Ekonomi Informasi');
INSERT INTO offerred VALUES ('ISM403', 'Etika Agama Profesionalisme dan Legal');
INSERT INTO offerred VALUES ('IKH328', 'Forensik Komputer dan Jaringan');
INSERT INTO offerred VALUES ('IKG402', 'Grafika Komputer');
INSERT INTO offerred VALUES ('UBA402', 'Internasionalisasi');
INSERT INTO offerred VALUES ('IKH313', 'Jaringan Komputer dan Keamanan');
INSERT INTO offerred VALUES ('IKH327', 'Keamanan Fisisk');
INSERT INTO offerred VALUES ('IKH323', 'Keamanan Informasi');
INSERT INTO offerred VALUES ('UKT101', 'Kuliah Kerja Lapangan');
INSERT INTO offerred VALUES ('IKB250', 'Kuliah Kerja Profesi');
INSERT INTO offerred VALUES ('IKP321', 'Manajemen dan Kualitas Perangkat Lunak');
INSERT INTO offerred VALUES ('IKD312', 'Manajemen Data dan Informasi');
INSERT INTO offerred VALUES ('ISM401', 'Manajemen Proyek Teknologi Informasi');
INSERT INTO offerred VALUES ('IKS304', 'Metode Berorientasi Obyek');
INSERT INTO offerred VALUES ('IKH316', 'Model dan Arsitektur Keamanan Informasi');
INSERT INTO offerred VALUES ('IKH351', 'Organisasi dan Arsitektur Komputer');
INSERT INTO offerred VALUES ('UKW400', 'Pancasila dan Kewarganegaraan');
INSERT INTO offerred VALUES ('IKL233', 'Pemodelan Geometri');
INSERT INTO offerred VALUES ('IKP302', 'Pemprog Berbasis Komponen');
INSERT INTO offerred VALUES ('IKP311', 'Pemrograman Berbasis Web');
INSERT INTO offerred VALUES ('IKH329', 'Pengelolaan Keamanan Informasi');
INSERT INTO offerred VALUES ('IKH342', 'Pengolahan Sinyal Dijital');
INSERT INTO offerred VALUES ('IKB405', 'Penulisan Ilmiah dan Laporan');
INSERT INTO offerred VALUES ('IKH326', 'Perencanaan Kontinyuitas Bisnis');
INSERT INTO offerred VALUES ('IKL141', 'Prak Struktur Data dan Algorithma');
INSERT INTO offerred VALUES ('IKH118', 'Prakt. Verifikasi dan Validasi Keamanan Informasi');
INSERT INTO offerred VALUES ('IKH128', 'Praktikum Forensik Komputer dan Jaringan');
INSERT INTO offerred VALUES ('IKG101', 'Praktikum Grafika Komputer');
INSERT INTO offerred VALUES ('IKH113', 'Praktikum Jaringan Komputer dan Keamanan');
INSERT INTO offerred VALUES ('IKH110', 'Praktikum Keamanan Jaringan Komputer');
INSERT INTO offerred VALUES ('IKP102', 'Praktikum Pemrograman Berbasis Komponen');
INSERT INTO offerred VALUES ('IKH109', 'Praktikum Pengelolaan Keamanan Informasi');
INSERT INTO offerred VALUES ('IKG121', 'Praktikum Rekayasa Sistem Multimedia');
INSERT INTO offerred VALUES ('IKH111', 'Praktikum Sistem Operasi');
INSERT INTO offerred VALUES ('ISM404', 'Proyek Rekayasa');
INSERT INTO offerred VALUES ('ISD305', 'Rekayasa Data dan Pengetahuan');
INSERT INTO offerred VALUES ('IKG321', 'Rekayasa Sistem Multimedia');
INSERT INTO offerred VALUES ('IKS308', 'Sistem Informasi Manajemen');
INSERT INTO offerred VALUES ('IKH310', 'Sistem Keamanan Jaringan');
INSERT INTO offerred VALUES ('IKH311', 'Sistem Operasi');
INSERT INTO offerred VALUES ('IKH314', 'Sistem Pengendalian Akses');
INSERT INTO offerred VALUES ('IKL341', 'Struktur Data dan Algoritma');
INSERT INTO offerred VALUES ('IUM461', 'Struktur Diskrit I');
INSERT INTO offerred VALUES ('IKS413', 'Technopreneurship');
INSERT INTO offerred VALUES ('ISD314', 'Teknik Data Mining');
INSERT INTO offerred VALUES ('IKB450', 'Tugas Akhir I');
INSERT INTO offerred VALUES ('IKB451', 'Tugas Akhir II');
INSERT INTO offerred VALUES ('IKH318', 'Verifikasi dan Validasi Keamanan Informasi');
INSERT INTO offerred VALUES ('IKS318', 'Verifikasi dan Validasi Perangkat Lunak');

